---
abstract: 'Basic infrastructure for writing asynchronous socket service'
author:
  - 'Sebastiano Piccoli <sebastiano.piccoli@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Storable: 0
  Test::Fatal: 0
  Test::More: 0.88
  utf8: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Asyncore
provides:
  Asyncore:
    file: lib/Asyncore.pm
    version: 0.04
  Asyncore::Dispatcher:
    file: lib/Asyncore.pm
    version: 0.04
requires:
  Carp: 0
  IO::Select: 0
  IO::Socket::INET6: 0
  base: 0
  constant: 0
  integer: 0
  overload: 0
  perl: 5.008001
  strict: 0
  vars: 0
  warnings: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.05
